"""
Project configurations — one entry per brand.
To add a new project: copy an existing block and fill in the mappings.
"""

PROJECTS = {

    # ─── T-SLOTS (TraceParts raw xlsx) ───────────────────────────────────────
    "T-Slots (TraceParts)": {
        "description": "TraceParts CAD download leads for Bonnell Aluminum T-Slots",
        "input_format": "xlsx",
        "source_type": "traceparts",
        "merge_by": "Email",
        "lead_intro": "This is a registered user who has downloaded the CAD drawing for T SLOTS.",
        "lead_outro": "Please contact the customer for services or product opportunities.",
        "lead_source_1": "Traceparts",
        "lead_source_2": "CAD Downloads",
        "col_map": {
            "FirstName":     "First name",
            "LastName":      "Name",
            "ContactTitle":  "Job",
            "Company":       "Company",
            "Address":       ["Address1", "Address2", "Address3"],
            "City":          "City",
            "State":         "State (USA)",
            "ZipCode":       "Zip/Postal Code",
            "Country":       "Country name",
            "PhoneSupplied": "Phone",
        },
        "comment_fields": [
            ("Part number",               "Part number"),
            ("Part description",          "Part description"),
            ("CAD Format",                "CAD format"),
            ("Date",                      "Date"),
            ("Status",                    "Status"),
            ("Origin (Web site)",         "Origin (Web site)"),
            ("Catalog",                   "Catalog"),
            ("Opt-in (emailing allowed)", "Opt-in (emailing allowed)"),
        ],
    },

    "Tsubaki": {
        "description": "Tsubaki CAD user downloads from Thomasnet — xlsx or msg with xlsx attachment",
        "input_format": "auto",
        "source_type": "tsubaki",
        "merge_by": "Email",
        "lead_source_1": "Website",
        "lead_source_2": "CAD Downloads",
        "col_map": {
            "FirstName":     "FirstName",
            "LastName":      "LastName",
            "ContactTitle":  "",
            "Company":       "Company",
            "Address":       [],
            "City":          "",
            "State":         "",
            "ZipCode":       "Zip",
            "Country":       "Country",
            "PhoneSupplied": "",
        },
        "comment_fields": [],
        "comment_template": "tsubaki",
    },

    "Watts Batch": {
        "description": "Watts CEU/Webinar leads — Notes to Rep with hyperlinks, no deduplication",
        "input_format": "auto",
        "source_type":  "watts_batch",
        "merge_by":     "Email",
        "lead_source_1": "",
        "lead_source_2": "",
        "lead_source_3": "",
        "col_map": {
            "FirstName":   "User First Name",
            "LastName":    "User Last Name",
            "Email":       "User's Email (ignoring user display setting)",
            "Company":     "Company Name",
            "City":        "User's City",
            "State":       "State/Province",
            "Country":     "Country",
            "ZipCode":     "Zip / Postal Code",
            "LeadSource1": "Lead Source 1",
            "LeadSource2": "Lead Source 2",
            "LeadSource3": "Lead Source 3",
            "Brand":       "Brand",
            "ContactTitle":"Customer Type ",
            "LeadComments":"Notes to Rep",
        },
        "comment_fields":    [],
        "comment_template":  "watts_batch",
    },

    "Universal / Batch": {
        "description": "Generic batch processor — upload any file, auto-detect columns, configure everything manually",
        "input_format": "auto",
        "source_type":  "universal",
        "merge_by":     "Email",
        "lead_intro":   "",
        "lead_outro":   "",
        "lead_source_1": "",
        "lead_source_2": "",
        "lead_source_3": "",
        "col_map":      {},
        "comment_fields": [],
    },
}
